# An initial workflow used for experimentation
name: Initial Workflow
on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  basic_job:
    name: Basic Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
            echo "Hello, ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
            echo "Current branch is '${{ github.ref }}'."
            echo "My secret is ${{ secrets.MAIN_SECRET }}."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: basic_job
    steps:
      - name: Test Job
        run: |
            echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: basic_job
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]
      
