# An initial workflow used for experimentation
name: Initial Workflow
on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  basic_job:
    name: Basic Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
            echo "Hello, ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
            echo "Current branch is '${{ github.ref }}'."
            echo "My secret is ${{ secrets.MAIN_SECRET }}."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - run: tree
      
